// Function that takes in another function as a parameter and calls and returns the function
// It is basically used to handle all the error generated by also invoking the Global Error Handler implemented
const catchAsync = (fn) => {
  return (req, res, next) => {
    fn(req, res, next).catch(next);
  };
};

module.exports = catchAsync;
